#!/usr/bin/env python3
"""
AI-Generated Repository Secret Scanner
=====================================
Advanced tool to identify AI-generated GitHub repositories and scan them for secrets using TruffleHog.

Detection Methods:
- Emoji usage analysis in README and commits
- GitHub Copilot usage indicators
- Unusual commit burst patterns
- Repository metadata analysis
- Code quality patterns

Author: HAYA Security Team
"""

import requests
import subprocess
import re
import json
import time
import sys
import os
import base64
import argparse
from datetime import datetime, timedelta
from collections import Counter, defaultdict
from urllib3.exceptions import InsecureRequestWarning
import statistics
from typing import List, Dict, Tuple, Optional
import tempfile
import shutil

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

class AIRepoSecretScanner:
    def __init__(self, github_token: str, trufflehog_path: str = "trufflehog"):
        self.github_token = github_token
        self.trufflehog_path = trufflehog_path
        self.session = requests.Session()
        self.session.headers.update({
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github+json',
            'User-Agent': 'AI-Repo-Scanner-HAYA/1.0'
        })
        
        # Rate limiting
        self.rate_limit_remaining = 5000
        self.rate_limit_reset = time.time() + 3600
        
        # AI detection thresholds
        self.AI_THRESHOLDS = {
            'emoji_count_readme': 10,           # Emojis in README
            'emoji_commit_ratio': 0.3,          # Ratio of commits with emojis
            'commit_burst_threshold': 20,       # Commits in short timeframe
            'commit_burst_window': 3600,        # 1 hour window
            'copilot_indicators': 3,            # Number of copilot indicators
            'min_confidence_score': 60          # Minimum AI confidence %
        }
        
        # Emoji pattern for detection
        self.emoji_pattern = re.compile("["
                                      u"\U0001F600-\U0001F64F"  # emoticons
                                      u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                                      u"\U0001F680-\U0001F6FF"  # transport & map symbols
                                      u"\U0001F700-\U0001F77F"  # alchemical symbols
                                      u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                                      u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                                      u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                                      u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                                      u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                                      u"\U00002702-\U000027B0"  # Dingbats
                                      u"\U000024C2-\U0001F251"
                                      "]+", flags=re.UNICODE)
        
        # Copilot indicators
        self.copilot_indicators = [
            r'github\.com/features/copilot',
            r'copilot.*generated',
            r'ai.*assistant',
            r'// generated by.*ai',
            r'# generated by.*ai',
            r'automatically generated',
            r'ai.*generated.*code',
            r'copilot.*suggestions'
        ]
        
        self.results = {
            'scanned_repos': 0,
            'ai_detected_repos': [],
            'secrets_found': [],
            'scan_timestamp': datetime.now().isoformat()
        }

    def log(self, message: str, level: str = "INFO"):
        """Enhanced logging with colors and timestamps"""
        timestamp = time.strftime("%H:%M:%S")
        colors = {
            "INFO": "\033[94m",
            "SUCCESS": "\033[92m", 
            "WARNING": "\033[93m",
            "ERROR": "\033[91m",
            "CRITICAL": "\033[95m",
            "AI_DETECTED": "\033[96m"
        }
        reset = "\033[0m"
        print(f"[{timestamp}] {colors.get(level, '')}{level}{reset}: {message}")

    def check_rate_limit(self):
        """Check and handle GitHub API rate limiting"""
        if self.rate_limit_remaining <= 100:
            wait_time = max(0, self.rate_limit_reset - time.time()) + 60
            self.log(f"Rate limit low ({self.rate_limit_remaining}), waiting {wait_time:.0f} seconds", "WARNING")
            time.sleep(wait_time)
            
    def update_rate_limit(self, response):
        """Update rate limit info from response headers"""
        if 'X-RateLimit-Remaining' in response.headers:
            self.rate_limit_remaining = int(response.headers['X-RateLimit-Remaining'])
        if 'X-RateLimit-Reset' in response.headers:
            self.rate_limit_reset = int(response.headers['X-RateLimit-Reset'])

    def search_repositories(self, query: str, max_results: int = 100) -> List[Dict]:
        """Search GitHub repositories with advanced filters"""
        self.log(f"Searching repositories: {query}")
        repositories = []
        page = 1
        per_page = min(100, max_results)
        
        while len(repositories) < max_results:
            self.check_rate_limit()
            
            params = {
                'q': query,
                'sort': 'updated',
                'order': 'desc',
                'per_page': per_page,
                'page': page
            }
            
            try:
                response = self.session.get('https://api.github.com/search/repositories', params=params)
                self.update_rate_limit(response)
                
                if response.status_code == 200:
                    data = response.json()
                    repos = data.get('items', [])
                    
                    if not repos:
                        break
                        
                    repositories.extend(repos)
                    self.log(f"Found {len(repos)} repositories (Total: {len(repositories)})")
                    page += 1
                    
                elif response.status_code == 403:
                    self.log("Rate limit exceeded, waiting...", "WARNING")
                    time.sleep(300)  # Wait 5 minutes
                    continue
                else:
                    self.log(f"API Error: {response.status_code} - {response.text}", "ERROR")
                    break
                    
            except Exception as e:
                self.log(f"Error searching repositories: {str(e)}", "ERROR")
                break
                
        return repositories[:max_results]

    def get_repository_content(self, owner: str, repo: str, path: str = '') -> Optional[str]:
        """Get repository file content"""
        self.check_rate_limit()
        
        try:
            url = f'https://api.github.com/repos/{owner}/{repo}/contents/{path}'
            response = self.session.get(url)
            self.update_rate_limit(response)
            
            if response.status_code == 200:
                data = response.json()
                if isinstance(data, list):
                    return None  # Directory listing
                    
                if data.get('encoding') == 'base64':
                    content = base64.b64decode(data['content']).decode('utf-8', errors='ignore')
                    return content
                    
            return None
            
        except Exception as e:
            self.log(f"Error getting content for {owner}/{repo}/{path}: {str(e)}", "ERROR")
            return None

    def get_commits(self, owner: str, repo: str, limit: int = 100) -> List[Dict]:
        """Get repository commits"""
        self.check_rate_limit()
        commits = []
        
        try:
            url = f'https://api.github.com/repos/{owner}/{repo}/commits'
            params = {'per_page': min(100, limit)}
            
            response = self.session.get(url, params=params)
            self.update_rate_limit(response)
            
            if response.status_code == 200:
                commits = response.json()
                
        except Exception as e:
            self.log(f"Error getting commits for {owner}/{repo}: {str(e)}", "ERROR")
            
        return commits[:limit]

    def analyze_emoji_usage(self, text: str) -> Dict:
        """Analyze emoji usage in text"""
        if not text:
            return {'count': 0, 'emojis': [], 'ratio': 0.0}
            
        emojis = self.emoji_pattern.findall(text)
        emoji_count = len(emojis)
        text_length = len(text.split())
        
        return {
            'count': emoji_count,
            'emojis': list(set(emojis)),
            'ratio': emoji_count / max(text_length, 1)
        }

    def analyze_commit_patterns(self, commits: List[Dict]) -> Dict:
        """Analyze commit patterns for AI indicators"""
        if not commits:
            return {'burst_detected': False, 'burst_count': 0, 'avg_interval': 0}
            
        timestamps = []
        emoji_commits = 0
        
        for commit in commits:
            try:
                commit_date = datetime.strptime(
                    commit['commit']['author']['date'], 
                    '%Y-%m-%dT%H:%M:%SZ'
                )
                timestamps.append(commit_date)
                
                # Check for emojis in commit message
                message = commit['commit']['message']
                if self.emoji_pattern.search(message):
                    emoji_commits += 1
                    
            except Exception as e:
                continue
                
        if len(timestamps) < 2:
            return {'burst_detected': False, 'burst_count': 0, 'avg_interval': 0}
            
        timestamps.sort()
        intervals = []
        
        for i in range(1, len(timestamps)):
            interval = (timestamps[i] - timestamps[i-1]).total_seconds()
            intervals.append(interval)
            
        avg_interval = statistics.mean(intervals) if intervals else 0
        
        # Detect commit bursts
        burst_count = 0
        current_burst = 1
        max_burst = 1
        
        for i in range(1, len(timestamps)):
            time_diff = (timestamps[i] - timestamps[i-1]).total_seconds()
            
            if time_diff < self.AI_THRESHOLDS['commit_burst_window']:
                current_burst += 1
            else:
                max_burst = max(max_burst, current_burst)
                current_burst = 1
                
        max_burst = max(max_burst, current_burst)
        
        return {
            'burst_detected': max_burst >= self.AI_THRESHOLDS['commit_burst_threshold'],
            'burst_count': max_burst,
            'avg_interval': avg_interval,
            'emoji_commit_ratio': emoji_commits / len(commits) if commits else 0,
            'total_commits': len(commits)
        }

    def detect_copilot_usage(self, owner: str, repo: str) -> Dict:
        """Detect GitHub Copilot usage indicators"""
        copilot_score = 0
        indicators_found = []
        
        # Check README for copilot mentions
        readme_content = self.get_repository_content(owner, repo, 'README.md')
        if not readme_content:
            readme_content = self.get_repository_content(owner, repo, 'readme.md')
            
        if readme_content:
            for indicator in self.copilot_indicators:
                if re.search(indicator, readme_content, re.IGNORECASE):
                    copilot_score += 1
                    indicators_found.append(f"README: {indicator}")
                    
        # Check for .copilot or AI-related files
        copilot_files = ['.copilot', '.github/copilot.yml', 'copilot.json', '.ai-generated']
        for file_path in copilot_files:
            content = self.get_repository_content(owner, repo, file_path)
            if content:
                copilot_score += 2
                indicators_found.append(f"File: {file_path}")
                
        return {
            'copilot_score': copilot_score,
            'indicators_found': indicators_found,
            'likely_copilot_usage': copilot_score >= self.AI_THRESHOLDS['copilot_indicators']
        }

    def calculate_ai_confidence(self, analysis_results: Dict) -> float:
        """Calculate AI generation confidence score"""
        confidence = 0.0
        
        # Emoji analysis weight
        if analysis_results['emoji_analysis']['readme_count'] > self.AI_THRESHOLDS['emoji_count_readme']:
            confidence += 25
            
        if analysis_results['emoji_analysis']['commit_ratio'] > self.AI_THRESHOLDS['emoji_commit_ratio']:
            confidence += 20
            
        # Commit pattern weight
        if analysis_results['commit_analysis']['burst_detected']:
            confidence += 30
            
        # Copilot usage weight
        if analysis_results['copilot_analysis']['likely_copilot_usage']:
            confidence += 25
            
        return min(confidence, 100.0)

    def analyze_repository(self, repo: Dict) -> Dict:
        """Comprehensive repository analysis for AI detection"""
        owner = repo['owner']['login']
        repo_name = repo['name']
        
        self.log(f"Analyzing repository: {owner}/{repo_name}")
        
        analysis = {
            'repository': f"{owner}/{repo_name}",
            'url': repo['html_url'],
            'created_at': repo['created_at'],
            'updated_at': repo['updated_at'],
            'stars': repo['stargazers_count'],
            'language': repo.get('language', 'Unknown')
        }
        
        # Get README content
        readme_content = self.get_repository_content(owner, repo_name, 'README.md')
        if not readme_content:
            readme_content = self.get_repository_content(owner, repo_name, 'readme.md')
            
        # Analyze emojis
        readme_emoji_analysis = self.analyze_emoji_usage(readme_content or '')
        
        # Get commits and analyze patterns
        commits = self.get_commits(owner, repo_name, 50)
        commit_analysis = self.analyze_commit_patterns(commits)
        
        # Detect Copilot usage
        copilot_analysis = self.detect_copilot_usage(owner, repo_name)
        
        # Combine analyses
        analysis.update({
            'emoji_analysis': {
                'readme_count': readme_emoji_analysis['count'],
                'readme_emojis': readme_emoji_analysis['emojis'],
                'commit_ratio': commit_analysis['emoji_commit_ratio']
            },
            'commit_analysis': commit_analysis,
            'copilot_analysis': copilot_analysis
        })
        
        # Calculate confidence score
        confidence = self.calculate_ai_confidence(analysis)
        analysis['ai_confidence'] = confidence
        analysis['is_likely_ai_generated'] = confidence >= self.AI_THRESHOLDS['min_confidence_score']
        
        return analysis

    def run_trufflehog_scan(self, repo_url: str) -> Dict:
        """Run TruffleHog scan on repository"""
        self.log(f"Running TruffleHog scan on: {repo_url}")
        
        try:
            # Create temporary directory for scan results
            with tempfile.TemporaryDirectory() as temp_dir:
                output_file = os.path.join(temp_dir, 'trufflehog_results.json')
                
                # Run TruffleHog
                cmd = [
                    self.trufflehog_path,
                    'git',
                    repo_url,
                    '--json',
                    '--output', output_file,
                    '--no-verification'
                ]
                
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=300  # 5 minute timeout
                )
                
                secrets_found = []
                
                # Parse results if output file exists
                if os.path.exists(output_file):
                    try:
                        with open(output_file, 'r') as f:
                            for line in f:
                                if line.strip():
                                    secret_data = json.loads(line.strip())
                                    secrets_found.append(secret_data)
                    except Exception as e:
                        self.log(f"Error parsing TruffleHog output: {str(e)}", "ERROR")
                
                # Also check stdout for secrets
                if result.stdout:
                    for line in result.stdout.strip().split('\n'):
                        if line.strip():
                            try:
                                secret_data = json.loads(line.strip())
                                secrets_found.append(secret_data)
                            except:
                                continue
                
                return {
                    'repository': repo_url,
                    'secrets_found': len(secrets_found),
                    'secrets': secrets_found,
                    'scan_successful': result.returncode == 0 or len(secrets_found) > 0,
                    'error_message': result.stderr if result.returncode != 0 else None
                }
                
        except subprocess.TimeoutExpired:
            self.log(f"TruffleHog scan timeout for: {repo_url}", "WARNING")
            return {
                'repository': repo_url,
                'secrets_found': 0,
                'secrets': [],
                'scan_successful': False,
                'error_message': 'Scan timeout'
            }
        except Exception as e:
            self.log(f"Error running TruffleHog scan: {str(e)}", "ERROR")
            return {
                'repository': repo_url,
                'secrets_found': 0,
                'secrets': [],
                'scan_successful': False,
                'error_message': str(e)
            }

    def scan_repositories(self, query: str, max_repos: int = 50) -> Dict:
        """Main scanning function"""
        self.log("=== AI Repository Secret Scanner Started ===", "SUCCESS")
        self.log(f"Search Query: {query}")
        self.log(f"Max Repositories: {max_repos}")
        
        # Search repositories
        repositories = self.search_repositories(query, max_repos)
        self.log(f"Found {len(repositories)} repositories to analyze")
        
        ai_detected_repos = []
        secrets_summary = []
        
        for i, repo in enumerate(repositories, 1):
            self.log(f"[{i}/{len(repositories)}] Analyzing: {repo['full_name']}")
            
            # Analyze repository for AI indicators
            analysis = self.analyze_repository(repo)
            self.results['scanned_repos'] += 1
            
            if analysis['is_likely_ai_generated']:
                self.log(f"AI-Generated Repository Detected! Confidence: {analysis['ai_confidence']:.1f}%", "AI_DETECTED")
                ai_detected_repos.append(analysis)
                self.results['ai_detected_repos'].append(analysis)
                
                # Run TruffleHog scan
                trufflehog_results = self.run_trufflehog_scan(repo['html_url'])
                
                if trufflehog_results['secrets_found'] > 0:
                    self.log(f"SECRETS FOUND: {trufflehog_results['secrets_found']} secrets in {repo['full_name']}", "CRITICAL")
                    secrets_summary.append({
                        'repository': repo['full_name'],
                        'url': repo['html_url'],
                        'secrets_count': trufflehog_results['secrets_found'],
                        'ai_confidence': analysis['ai_confidence']
                    })
                    self.results['secrets_found'].append(trufflehog_results)
                else:
                    self.log(f"No secrets found in {repo['full_name']}")
                    
                # Small delay to be respectful
                time.sleep(2)
            else:
                self.log(f"Repository appears human-generated (Confidence: {analysis['ai_confidence']:.1f}%)")
                
            # Progress update
            if i % 10 == 0:
                self.log(f"Progress: {i}/{len(repositories)} repositories processed")
                
        # Summary
        self.log("=== Scan Complete ===", "SUCCESS")
        self.log(f"Total Repositories Scanned: {len(repositories)}")
        self.log(f"AI-Generated Repositories Found: {len(ai_detected_repos)}")
        self.log(f"Repositories with Secrets: {len(secrets_summary)}")
        
        return {
            'scan_summary': {
                'total_scanned': len(repositories),
                'ai_detected': len(ai_detected_repos),
                'with_secrets': len(secrets_summary)
            },
            'ai_repositories': ai_detected_repos,
            'secrets_summary': secrets_summary,
            'full_results': self.results
        }

    def save_results(self, results: Dict, output_file: str):
        """Save scan results to JSON file"""
        try:
            with open(output_file, 'w') as f:
                json.dump(results, f, indent=2, ensure_ascii=False, default=str)
            self.log(f"Results saved to: {output_file}", "SUCCESS")
        except Exception as e:
            self.log(f"Error saving results: {str(e)}", "ERROR")

def main():
    parser = argparse.ArgumentParser(description='AI Repository Secret Scanner')
    parser.add_argument('--token', required=True, help='GitHub Personal Access Token')
    parser.add_argument('--query', default='stars:>10 created:>2023-01-01', 
                       help='GitHub search query')
    parser.add_argument('--max-repos', type=int, default=50, 
                       help='Maximum repositories to scan')
    parser.add_argument('--trufflehog-path', default='trufflehog', 
                       help='Path to TruffleHog binary')
    parser.add_argument('--output', default='ai_repo_scan_results.json', 
                       help='Output file for results')
    
    args = parser.parse_args()
    
    # Check if TruffleHog is available
    try:
        subprocess.run([args.trufflehog_path, '--version'], 
                      capture_output=True, timeout=10)
    except:
        print("ERROR: TruffleHog not found. Please install TruffleHog:")
        print("  curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin")
        sys.exit(1)
    
    scanner = AIRepoSecretScanner(args.token, args.trufflehog_path)
    
    try:
        results = scanner.scan_repositories(args.query, args.max_repos)
        scanner.save_results(results, args.output)
        
        # Print summary
        print("\n" + "="*80)
        print("SCAN SUMMARY")
        print("="*80)
        print(f"Total Repositories Scanned: {results['scan_summary']['total_scanned']}")
        print(f"AI-Generated Repositories: {results['scan_summary']['ai_detected']}")
        print(f"Repositories with Secrets: {results['scan_summary']['with_secrets']}")
        
        if results['secrets_summary']:
            print("\nREPOSITORIES WITH SECRETS:")
            for secret_repo in results['secrets_summary']:
                print(f"  • {secret_repo['repository']} - {secret_repo['secrets_count']} secrets (AI: {secret_repo['ai_confidence']:.1f}%)")
                
    except KeyboardInterrupt:
        print("\nScan interrupted by user")
    except Exception as e:
        print(f"Error during scan: {str(e)}")

if __name__ == "__main__":
    main()